# Generated by Django 4.0.4 on 2022-06-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_sizedimage_image_sizedimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizedTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='sizedImages',
        ),
        migrations.AddField(
            model_name='tier',
            name='sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier_user', to='imageapp.sizedtier'),
        ),
    ]
