# Generated by Django 4.0.4 on 2022-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_sizedtier_remove_image_sizedimages_tier_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='sizes',
        ),
        migrations.AddField(
            model_name='tier',
            name='sizes',
            field=models.ManyToManyField(null=True, related_name='tier_user', to='imageapp.sizedtier'),
        ),
    ]
