# Generated by Django 4.0.4 on 2022-06-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0004_remove_tier_sizes_tier_sizes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizedImage',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='thumbnail_size',
        ),
    ]
