# Generated by Django 4.0.4 on 2022-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0006_sizedimage_image_sizedimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='sizedImages',
        ),
        migrations.AddField(
            model_name='image',
            name='sizedImages',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizedimage_image', to='imageapp.sizedimage'),
        ),
    ]
